---
- name: install epel-release
  yum:
    name: epel-release
    state: present
  become: yes

- name: install pip
  yum:
    name: python-pip
    state: present
  become: yes

- name: update pip
  pip:
    name: pip
    extra_args: --upgrade
    state: present
  become: yes

- name: install docker-py
  pip:
    name: docker
    state: present
  become: yes