---
- name: install epel-release
  yum:
    name: epel-release
    state: present
  become: yes

- name: install docker-py
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "docker"
    - "docker-py"
  become: yes